- hosts: localhost
  connection: local
  sudo: no
  vars:
    dotfiles:
      - gemrc
      - gitconfig
      - gitignore_global
      - gitmessage.txt
      - tmux.conf
      - vimperatorrc
      - vimrc
      - zshenv
      - zshrc
      - vromerc
  tasks:
    # For zsh
    - name: oh-my-zsh のインストール
      git: repo=git://github.com/robbyrussell/oh-my-zsh.git
           dest={{ ansible_env.HOME }}/.oh-my-zsh

    - name: zsh-completionsのインストール
      git: repo=git://github.com/zsh-users/zsh-completions.git
           dest={{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-completions

    # For vim
    - name: create ~/.vim/ directory
      file: path={{ ansible_env.HOME }}/.vim/ state=directory mode=0755

    - name: ~/.vim/配下のディレクトリを設置
      file: src={{ ansible_env.PWD }}/vim/{{ item }} dest={{ ansible_env.HOME }}/.vim/{{ item }} state=link
      with_items:
        - dict
        - syntax
        - vimrc.d
        - template

    - name: create ~/.vim/bundle
      file: path={{ ansible_env.HOME }}/.vim/bundle state=directory

    # For vimperator
    - name: create ~/.vimperator
      file: path={{ ansible_env.HOME }}/.vimperator state=directory
      when: ansible_os_family == 'Darwin'

    - name: install vimperator-plugins
      git: repo=git@github.com:vimpr/vimperator-plugins.git
           dest={{ ansible_env.HOME }}/.vimperator/vimperator-plugins

    - name: link plugin_loader.js
      file: src={{ ansible_env.HOME }}/.vimperator/vimperator-plugins/plugin_loader.js dest={{ ansible_env.HOME }}/.vimperator/plugin/plugin_loader.js state=link

    # dotfilesの設置
    - name: 共通のdotfilesを設置
      file: src={{ ansible_env.PWD }}/{{ item }} dest={{ ansible_env.HOME }}/.{{ item }} state=link
      with_items:
        - gemrc
        - gitconfig
        - gitignore_global
        - gitmessage.txt
        - tmux.conf
        - vimperatorrc
        - vimrc
        - zshenv
        - zshrc
        - zshrc.darwin
        - zshrc.linux

    - name: zshrc.localをコピー
      copy: src={{ ansible_env.PWD }}/zshrc.local.sample dest={{ ansible_env.HOME }}/.zshrc.local force=no

    - name: for vimperator
      file: src={{ ansible_env.PWD }}/{{ item }} dest={{ ansible_env.HOME }}/.{{ item }} state=link
      with_items:
        - vimperator/colors
        - vimperator/plugin
        - vimperator/vimperator-plugins
      when: ansible_os_family == 'Darwin'
